services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
      target: build
    command: npm run dev --workspace=server
    working_dir: /usr/src/app
    env_file:
      - server/.env
    ports:
      - '4000:4000'
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: 'true'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    stdin_open: true
    tty: true

  client:
    build:
      context: .
      dockerfile: Dockerfile
      target: build
    env_file:
      - client/.env
    command: npm run dev --workspace=client -- --hostname 0.0.0.0 --port 3000
    working_dir: /usr/src/app
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: 'true'
      WATCHPACK_POLLING: 'true'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    stdin_open: true
    tty: true
